Sec 429 cleanup
introlab/securbot pull request #43
Opened 2019-04-24 00:45 UTC by MoronixProduct3

### Launch file cleanup
- Removed old launch files which are no longer relevant to the project.
- Created a new `securbot_demo.launch`  in `launch/demo/` which can do teleportation and way-point patrol at the same time.
- Fixed merge issues with electron node.
- Fixed syntactic errors in the patrolExecutive node.

2019-04-24 19:50 UTC, GodCed reviewed
Ça a l'air bien du côté de securbot_pkg.

@edouard1195 Dans electron webrtc il a un launchfile vnf_electron. Est-ce qu'il est encore d'actualité ou a-t-il été complètement remplacé?

2019-04-24 21:37 UTC, edouard1195 requested changes
@GodCed English!
I have no idea what the vnf thing is, it was already there when I started working on the Electron app. I never used it though (I used the other script file done by the other Edouard) so unless it is called deep somewhere, i think it can be deleted.

@MoronixProduct3 
I have no problem with the changes in the electron app, but the documentation part won't work properly unless you also change the "@Fires" tag in the function description (the one that contains the events, in main.js the function is startNode). So change that and the Electron app will be good to go.

Discussion : 
Do we really want the teleop and patrol to work at the same time right now ? Since we haven't implemented a behavior manager (like hbba), I am not really sure it is a good idea since it could caused a lot of problems that we won't be able to fix in the next 4 months. That being said, I haven't seen the robot work with both at the same time so it could fine, but I might have a few idea on how everything could burn because of this. What's your opinion on this ?

2019-04-24 22:00 UTC, edouard1195 approved these changes

2019-04-24 22:01 UTC, MoronixProduct3 commented
The `vnf_electron` launch file allows us to run the electron app in a machine without a graphics device. The only difference with the other one is the `--disable-gpu` flag in the script it calls. We don't currently need that launch file. We can keep the script file associated with it.

2019-04-25 13:49 UTC, GodCed approved these changes

2019-04-25 18:01 UTC, merged